remote_theme: devich/quick@0.0.1
lang: en-US
bg_color: dark
theme_color: cyan
title: "DomLabs | Innovating the Future"
description: "DomLabs is a technology company founded by Dominick David Derenthall, building innovative tools like GuardBox, SnackBot, and DevDock."
keywords: "DomLabs, Dominick Derenthall, SnackBot, GuardBox, DevDock, AI, Security, Productivity, Innovation"
