remote_theme: devich/quick@0.0.1
lang: en-US
bg_color: black
theme_color: cyan
title: "DomLabs | Innovating the Future"
description: "DomLabs — created by Dominick Derenthall — builds focused, secure, and intelligent tools like GuardBox, SnackBot, and DevDock."
keywords: "DomLabs, Dominick Derenthall, SnackBot, GuardBox, DevDock, Security, Productivity, AI, Coding Tools, Tech Company"
